import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/modules/header/header";
import Footer from "@/components/modules/footer/footer";
import { Shantell_Sans } from "next/font/google";

const geist = Shantell_Sans({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["cyrillic", "cyrillic-ext", "latin", "latin-ext"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geist.className}`} suppressHydrationWarning>
        <div className="flex flex-col h-dvh">
          <Header />
          <main className="flex-1">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
